### PR TITLE
feat(designer): Add utility for extracting UI from tokens ad hoc

### PR DESCRIPTION
**Pull request by MStmaul**
Takes in a workflow definition and basic services to return back Token UI data. 

Needed for our case, where we store only token value data on the backend, so have to build the token UI from that outside the context of the designer.

### CODE REVIEW

**Review by preetriti1 — CHANGES_REQUESTED** [review]
Please setup sometime with our team for a design discussion before making these changes. We do not want to keep dispatches as optional else it will break the initialization process, if you need to add capability for your scenario we should discuss on what can be exposed and how it needs to be exposed for design.

**Comment by MStmaul** [comment]
Messaged offline.

**Comment by MStmaul** [comment]
Going to discuss further when GA release cools down... For now doing this in our repo.

**Comment by hartra344** [comment]
I'm going to close this for now so we can discuss correct way we want to handle this for productization.

**Pull request closed without merging**
