### PR TITLE
fix(Designer): Keyboard Focus Moves Out of TokenPicker Navigating Using Keyboard

### LINKED ISSUE #4042: Keyboard focus move outside of the 'Insert dynamic content' dialog while navigating using keyboard.
### Describe the issue 

[https://msazure.visualstudio.com/One/\_workitems/edit/26532506](<https://msazure.visualstudio.com/One/_workitems/edit/26532506>)

User Experience:

Keyboard user will face difficulty to navigate the control of dialog, if Keyboard focus moves outside the 'dialogue, user who depend on keyboard will need to perform an extra navigation to reach the control.

Note: User credentials should NOT be included in the bug.

Pre-requisites:

Make sure dependencies such as Azure Logic Apps (Standard), Azure Functions, C# are installed.

Navigate to Azure control present on the right side and select it.

Navigate to LogicApp icon present under workspace section, click on that and select 'Create New Project'.

Navigate select stateful workflow, then enter the name of the workflow.

Once the workflow has been created then enter the name of the created workflow in edit field present on the top and press Enter.

Navigate to 'Open in current window' and select it.

A dialog will appear, select 'Yes', now the workflow will open in new window.

Repro Steps:

Open Visual Studio app.

Navigate to any workflow and right click on it, then select 'open designer'.

Navigate to send message box and select it, a new blade appears on right side.

Navigate all the controls of 'Parameters' tab.

Navigate to Relative path edit field and then type '/' in inputs edit field present under 'Parameter' tab and then press enter.

Navigate through all the options a user is getting after typing '/'.

Observe weather Keyboard focus move outside of the 'Insert dynamic content' dialog while navigating using keyboard or not.

Actual Result:

Keyboard focus move outside of the 'Insert dynamic content' dialog while navigating using keyboard.

Observation: After Learn more about dynamic link for next tab key focus is moving outside the 'Insert dynamic content' dialog, the focus is moving to save button.

Expected result:

Keyboard focus should not move outside the 'Insert dynamic content' dialog while navigating using keyboard.

Example: After Learn more about dynamic link for next tab key focus should land on first interactive element in the dialog.

ARIA Authoring Ref Link/Fluent Patterns Guidance /HITS Guidance/previous test pass bug id's:

N/A

UIA/DOM details available:

N/A

MAS Reference:

[MAS 2.4.3 – Focus Order](<https://microsoft.sharepoint.com/:w:/r/sites/accessibility/_layouts/15/Doc.aspx?sourcedoc=%7b80A4F009-8781-4423-B3CD-2448EAF5BF62%7d&file=MAS%202.4.3%20%E2%80%93%20Focus%20Order.docx&action=default&mobileredirect=true>)

Reference Links:

[Accessibility Insights!](<https://accessibilityinsights.io/>) \- Identify accessibility bugs before check-in and make bug fixing faster and easier.

External Bug Process: If this bug belongs to external team, mark it as resolved/done and assign it back to the tester with notes on where to file/route the bug. For more information please use this [External Bug Process (sharepoint.com)](<https://microsoft.sharepoint.com/teams/cea11y/SitePages/External-Bug-Process.aspx?xsdata=MDN8MDF8fDE1MThmM2JlZGFjMDRlZDhiZmViYTUxMDA2M2NiZWI3fDcyZjk4OGJmODZmMTQxYWY5MWFiMmQ3Y2QwMTFkYjQ3fDF8MHw2Mzc3NDEyNTM2MTEzNzIwNzR8R29vZHxWR1ZoYlhOVFpXTjFjbWwwZVZObGNuWnBZMlY4ZXlKV0lqb2lNQzR3TGpBd01EQWlMQ0pRSWpvaUlpd2lRVTRpT2lJaUxDSlhWQ0k2TVRKOQ%3D%3D&sdata=MnlpSXlVMnpGT3cvZ0xJNnFWUWZWTGt6dmo1VkJMZFpIZHBvUUduNDhyMD0%3D&ovuser=72f988bf-86f1-41af-91ab-2d7cd011db47%2cv-kgeetala%40microsoft.com>). “HCL Staff should not log any third party external bugs. Should be routed to EDAD team”.

Please reach out to [C&AI Teams channel](<https://apc01.safelinks.protection.outlook.com/?url=https://teams.microsoft.com/l/team/19%253a3cd071821b694f11b054d878453cd75f%2540thread.skype/conversations?groupId%3D30e3f968-15dd-4da2-bd8e-85f27e4af2c3%26tenantId%3D72f988bf-86f1-41af-91ab-2d7cd011db47&data=02%7c01%7cAklavyaM%40hcl.com%7c24e89c6ac26f42cfe40c08d7667e49f3%7c189de737c93a4f5a8b686f4ca9941912%7c0%7c0%7c637090564906844600&sdata=22JjBMoA1ID/KnYqFa/OB%2BrkTaLh5YYsGBd/7Bm7u5w%3D&reserved=0>) for any process-related queries.

### Are you using new designer or old designer 

New Designer (With action panels)

### Screenshots or Videos 

*No response*

### Browser 

Chrome

### Additional context 

*No response*

### PR DESCRIPTION
**Pull request by Elaina-Lee**
- **Please check if the PR fulfills these requirements**

* [X] The commit message follows our guidelines

- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
fixes #4042 
- **What is the current behavior?** (You can also link to an open issue here)
in tokenpicker, moving by keyboard takes the focus away to somewhere irrelevant
- **What is the new behavior (if this is a feature change)?**
in tokenpicker, moving by keyboard stays within tokenpicker unless esc is pressed
- **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

- **Please Include Screenshots or Videos of the intended change**:

https://github.com/Azure/LogicAppsUX/assets/144840522/12390b19-7ff5-4794-924c-1e88a9f9ab4a

### CODE REVIEW

**Review by hartra344 — APPROVED** [review]

**Comment by Eric-B-Wu** [comment]
this causes a weird little bug where if you have a token in the editor, and press tab you can get multiple tokenpicker buttons:

https://github.com/Azure/LogicAppsUX/assets/95886809/f0177c36-14e3-419e-b44b-fd63bba35d22

**Comment by Elaina-Lee** [comment]
> this causes a weird little bug where if you have a token in the editor (html editor doesn't need it due to the toolbar), and press tab you can get multiple tokenpicker buttons:
> 
>  Screen.Recording.2024-02-09.at.11.50.51.AM.mov

I checked out the main branch and am still seeing the weird little bug. Would you be able to double check if the bug persists on main to confirm my change is causing the issue?

https://github.com/Azure/LogicAppsUX/assets/144840522/a6eae1aa-62bd-442a-8c24-616502a56081

**Comment by Eric-B-Wu** [comment]
> > this causes a weird little bug where if you have a token in the editor (html editor doesn't need it due to the toolbar), and press tab you can get multiple tokenpicker buttons:
> > Screen.Recording.2024-02-09.at.11.50.51.AM.mov
> 
> I checked out the main branch and am still seeing the weird little bug. Would you be able to double check if the bug persists on main to confirm my change is causing the issue?
> 
>  tokenPickerFocus.bug-1.mp4
is this from main? because it doesn't seem to be happening here - in my other branch i currently have checked out from main this issue isn't happening

**Comment by Elaina-Lee** [comment]
> > > this causes a weird little bug where if you have a token in the editor (html editor doesn't need it due to the toolbar), and press tab you can get multiple tokenpicker buttons:
> > > Screen.Recording.2024-02-09.at.11.50.51.AM.mov
> > 
> > 
> > I checked out the main branch and am still seeing the weird little bug. Would you be able to double check if the bug persists on main to confirm my change is causing the issue?
> > tokenPickerFocus.bug-1.mp4
> > is this from main? because it doesn't seem to be happening here - in my other branch i currently have checked out from main this issue isn't happening

Thanks for confirming, must be my local ends problem. I'll clear cache and try again!

**Comment by Elaina-Lee** [comment]
> > > this causes a weird little bug where if you have a token in the editor (html editor doesn't need it due to the toolbar), and press tab you can get multiple tokenpicker buttons:
> > > Screen.Recording.2024-02-09.at.11.50.51.AM.mov
> > 
> > 
> > I checked out the main branch and am still seeing the weird little bug. Would you be able to double check if the bug persists on main to confirm my change is causing the issue?
> > tokenPickerFocus.bug-1.mp4
> > is this from main? because it doesn't seem to be happening here - in my other branch i currently have checked out from main this issue isn't happening

I have addressed the issue and fixed it.

https://github.com/Azure/LogicAppsUX/assets/144840522/e56c6755-f830-45b1-a76b-024656a6d8b9

**Review by Eric-B-Wu — APPROVED** [review]

**Pull request merged**
