### PR TITLE
feat: Adding UI for NL2F Expression Assistant and Copilot Service Interface

### PR DESCRIPTION
**Pull request by maturpi**
- **Please check if the PR fulfills these requirements**

* [ ] The commit message follows our guidelines
* [ ] Tests for the changes have been added (for bug fixes/features)
* [ ] Docs have been added / updated (for bug fixes / features)

- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Feature

- **What is the current behavior?** (You can also link to an open issue here)
N/A

- **What is the new behavior (if this is a feature change)?**
N/A

- **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

- **Please Include Screenshots or Videos of the intended change**:
nl2fExpressionUIDemo

### CODE REVIEW

**Comment by maturpi** [comment]
Let me know if there's anything wrong with the following files that go modified automatically when merging master and doing commits (commit hooks):

Localize/lang/strings.json
package-lock.json
pnpm-lock.yaml

**Comment by hartra344** [comment]
please update with main and run pnpm with at least version 9 of pnpm

**Comment by hartra344** [comment]
Closing for now for clean up, reopen when updated and ready to review. Also please when reopening, mark that owners of the repo can make updates, would have been possible for me to update to main for you and get passing tests if you had.

**Comment by maturpi** [comment]
Checked the 'Allow edits and access to secrets by maintainers' checkbox.

**Pull request closed without merging**
