### PR TITLE
fix(designer): Fixed style change for token picker

### PR DESCRIPTION
**Pull request by spanvalkar**

### CODE REVIEW

**Comment by hartra344** [comment]
how important is this for you? I'm hesitant to bring this change in while we're prepping for GA/release because of the issues it could potentially cause.

**Comment by spanvalkar** [comment]
This change fixes this bug: https://dev.azure.com/msazure/One/_workitems/edit/20553107

It's a style/appearance change, so it could potentially be pushed out. What issues do you foresee that may happen?

**Comment by hartra344** [comment]
> This change fixes this bug: https://dev.azure.com/msazure/One/_workitems/edit/20553107
> 
> It's a style/appearance change, so it could potentially be pushed out. What issues do you foresee that may happen?

What I'm worried most about is that it was done for portal integration on our side and that remove it and moving that much lower will cause things not to show up in our portal. We've already gotten to our "ask mode" for our GA release so I don't want to take anything that would add extra risk to that.

**Comment by spanvalkar** [comment]
That sounds reasonable. Let's keep this PR open for now and we can review/merge after the GA release is complete for you.

Within what timeframe do you estimate that we can merge this change?

**Comment by Eric-B-Wu** [comment]
Our GA release has already taken a snapshot of new designer and is in our testing environment. However, we'll be rolling out hotfixes to the branch throughout the week as we fix customer/vendor testing bugs. The release will complete 05/19

**Comment by hartra344** [comment]
We will be in ask mode however until BUILD in case there are important fixes that need to go in

**Review by Eric-B-Wu — APPROVED** [review]

**Pull request merged**
