### PR TITLE
chore(designer): Replace `panel` with `panelV2`

### PR DESCRIPTION
**Pull request by ek68794998**
## Requirement Checklist

* [x] The commit message follows our guidelines
* [x] Tests for the changes have been added (for bug fixes or features)
* [ ] Docs have been added or updated (for bug fixes or features)

## Type of Change

* [ ] Bug fix
* [ ] Feature
* [x] Other

## Current Behavior

The `panelV2` slice was added in #5202, and was used as a steppingstone to keep changesets small and digestible.

## New Behavior

Now that pinning has been stabilized, this PR cleans up the `panel`&ndash;`panelV2` state relationship. The old `panel` state slice has been removed, and `panelV2` has been renamed to `panel`, completely replacing the original.

**Note:** I tried to keep this as clean as possible, but even doing `git mv panelV2 panel` did not track the folder rename as a move. As a result, `panelSelectors.ts` and `panelSlice.ts` diffs are really poor. :(

## Impact of Change

* [x] **This is a breaking change.**

Host services using the package no longer have access to the functions:

- `useSelectedNodeId`
- `useSelectedNodeIds`

Depending on use case, those calls should be replaced with one of:

- `useConnectionPanelSelectedNodeIds`
- `useDiscoveryPanelSelectedNodeIds`
- `useOperationPanelSelectedNodeId`

In addition, anyone directly reading the `panel` state in their host service may no longer be able to reference the fields that they were previously.

## Screenshots or Videos (if applicable)

I ran through some test cases which can be seen below.

e2e-1

e2e-2

### CODE REVIEW

**Comment by hartra344** [comment]
This looks awesome! Just be aware we're probably going to be super picky and careful with this PR because of the pain that's been caused by panel changes recently.

**Comment by ek68794998** [comment]
> This looks awesome! Just be aware we're probably going to be super picky and careful with this PR because of the pain that's been caused by panel changes recently.

Yeah, no problem. I just didn't want to leave the panel in a half-baked state.

If there's anything I can do on my side to help build confidence in the change, please let me know.

**Comment by hartra344** [comment]
> > This looks awesome! Just be aware we're probably going to be super picky and careful with this PR because of the pain that's been caused by panel changes recently.
> 
> Yeah, no problem. I just didn't want to leave the panel in a half-baked state.
> 
> If there's anything I can do on my side to help build confidence in the change, please let me know.

Some E2E tests of the basic functionality both old expected behavior and new behavior (mock tests should be fine and they're very quick to write) would definitely be a big confidence booster.

**Comment by ek68794998** [comment]
> > > This looks awesome! Just be aware we're probably going to be super picky and careful with this PR because of the pain that's been caused by panel changes recently.
> > 
> > 
> > Yeah, no problem. I just didn't want to leave the panel in a half-baked state.
> > If there's anything I can do on my side to help build confidence in the change, please let me know.
> 
> Some E2E tests of the basic functionality both old expected behavior and new behavior (mock tests should be fine and they're very quick to write) would definitely be a big confidence booster.

I added some tests for very basic panel scenarios (select operation, pin operation, change tabs). Do you have any specific scenarios in which you've seen regressions in the past, that you think would be worthwhile covering?

I also thought of testing the connections UI but not sure if I can mock that or not.

**Review by rllyy97 — APPROVED** [review]

**Comment by rllyy97** [comment]
Looks great Eric thanks for all your work on this!

**Comment by ek68794998** [comment]
Holding off merging until @preetriti1 has a chance to review.

**Comment by ccastrotrejo** [comment]
Just for a general understanding on this. What is the idea or difference between the new 3 selectors?
- useConnectionPanelSelectedNodeIds
- useDiscoveryPanelSelectedNodeIds
- useOperationPanelSelectedNodeId

**Comment by ek68794998** [comment]
> Just for a general understanding on this. What is the idea, difference between the new 3 selectors or which panel is whic?
> 
> * useConnectionPanelSelectedNodeIds
> * useDiscoveryPanelSelectedNodeIds
> * useOperationPanelSelectedNodeId

The idea of selected nodes differs between panels. The biggest example being that the operation panel cannot have more than one node selected at once (ignoring the pinned node, which is a different field).

Additionally, there are panels (such as search panel or errors panel) which do not support selected nodes at all. As a result, all of the `selectedNodeId(s)` fields have been moved inside one of the `state.*Content` objects.

Right now, they are kept in sync because that's how they've been set up so far:

image

However, the idea would be that these _can_ be different based on which panel is shown, and ideally these `setSelectedNodeId(s)` methods should be broken out into their respective panel versions.

**Review by preetriti1 — APPROVED** [review]

**Pull request merged**
