### PR TITLE
fix(designer): Show error message when using invalid payload in schema editor

### PR DESCRIPTION
**Pull request by Eric-B-Wu**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
bugfix

* **What is the current behavior?** (You can also link to an open issue here)
no error message is shown and is defaulted to {}

* **What is the new behavior (if this is a feature change)?**
error message is shown, value is not changed

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
no

* **Please Include Screenshots or Videos of the intended change**:

### CODE REVIEW

**Review by ccastrotrejo — APPROVED** [review]

**Review by rllyy97 — APPROVED** [review]

**Comment by preetriti1** [comment]
screenshot?

**Comment by Eric-B-Wu** [comment]
showerror
This was just the error that was showing, but I think there was a try catch added to default to {}, which would avoid showing the error then

**Comment by preetriti1** [comment]
> showerror This was just the error that was showing previously, but I think there was a try catch added to default to {}, which would avoid showing the error then

Just make sure filter array action is working fine when you pass in a array token

**Comment by Eric-B-Wu** [comment]
> > showerror
> >       
> >         [
> >           
> >         
> >             showerror
> >           ](https://user-images.githubusercontent.com/95886809/243445437-f486f393-1f13-47b0-909c-78899939de57.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/95886809/243445437-f486f393-1f13-47b0-909c-78899939de57.gif)
> >         
> >        This was just the error that was showing previously, but I think there was a try catch added to default to {}, which would avoid showing the error then
> 
> Just make sure filter array action is working fine when you pass in a array token

just checked and it is working

**Pull request merged**
